### ISSUE TITLE
Cleaning node variables

### ISSUE THREAD

**Issue by KamilWdowczyk** [gmclan-org/dijkstra-graph#1]
https://github.com/gmclan-org/dijkstra-graph/blob/5b705011b59d50f766ffc7107a222b7c1f26e278/objects/obj_editor/Mouse_53.gml#L44-L57

Line 54: Why reseting to -2 ?

**Comment by gnysek** [comment]
I probably took `2` from variable name (`node2`)... Of course it should be `-1` .

![](https://media.bizj.us/view/img/11596989/mistake*1024xx5616-3171-0-430.jpg)
